---
title: "Final Project Markdown"
author: "Carly Gottorff"
date: "November 27, 2018"
output: html_document
---

```{r}
library("RSQLite")
#Connect to data 
db <- dbConnect(SQLite(),"C:/Users/cgott/Documents/ST449/Datasets/database.sqlite")
## list all tables
tables <- dbListTables(db)
#Creating DF for each table
Country <- dbGetQuery(db,"Select * from Country")
League <- dbGetQuery(db,"Select * from League")
Match <- dbGetQuery(db,"Select * from Match")
Player <- dbGetQuery(db,"Select * from Player")
Player_Attributes <- dbGetQuery(db,"Select * from Player_Attributes")
Team <- dbGetQuery(db,"Select * from Team")
Team_Attributes <- dbGetQuery(db,"Select * from Team_Attributes")

```


```{r}
#Data Cleaning

#extracting data by English league 
leagueSplit<-dbGetQuery(db,"SELECT  league_id, season, home_team_api_id,
            away_team_api_id, home_team_goal, away_team_goal, date, match_api_id
           FROM Match 
           WHERE league_id='1729' ")

#B365H, B365A, B365D, BWH, BWA, BWD, IwA, IWH, IWD, LBH, LBA, LBD, PSH, PSD, PSA, WHA,WHH, WHD, SJA,SJD,SJH, VCA,VCH,VCD,GBA, GBH, GBD, BSH, BSA, BSD

#counting number of away matches for each team with long name
gamesPlayedAway<-dbGetQuery(db, "SELECT away_team_api_id, team_long_name, COUNT(away_team_api_id)
           FROM Match JOIN Team
            ON Match.away_team_api_id= Team.team_api_id
           WHERE league_id='1729'
           GROUP BY away_team_api_id")
#counting number of home matches for each team
gamesPlayedHome<-dbGetQuery(db, "SELECT home_team_api_id, COUNT(home_team_api_id)
           FROM Match 
           WHERE league_id='1729'
           GROUP BY home_team_api_id")

#merging away and home matches
colnames(gamesPlayedAway)<-c("team_api_id","team_long_name", "away_games")
colnames(gamesPlayedHome)= c("team_api_id", "home_games")
gamesPlayedAH<-merge(gamesPlayedAway, gamesPlayedHome, by="team_api_id")
#adding total games
gamesPlayedAH$totalPlayed<-(gamesPlayedAH$away_games+gamesPlayedAH$home_games)
```


```{r}
#creating outcome varibales for win, lose, tie for home team to count number of each for descriptive stats 
for (i in 1:nrow(leagueSplit)){
  if(leagueSplit$home_team_goal[i]==leagueSplit$away_team_goal[i]){
    leagueSplit$homeTie[i]=1
  } else{
    leagueSplit$homeTie[i]=0
  }
  if(leagueSplit$home_team_goal[i]>leagueSplit$away_team_goal[i]){
    leagueSplit$homeWin[i]=1
  }else{
    leagueSplit$homeWin[i]=0
  }
  if(leagueSplit$home_team_goal[i]<leagueSplit$away_team_goal[i]){
    leagueSplit$homeLose[i]=1
  }else{
    leagueSplit$homeLose[i]=0
  }
}
#creating win lose tie for away team
for (i in 1:nrow(leagueSplit)){
  if(leagueSplit$home_team_goal[i]==leagueSplit$away_team_goal[i]){
    leagueSplit$awayTie[i]=1
  } else{
    leagueSplit$awayTie[i]=0
  }
  if(leagueSplit$away_team_goal[i]>leagueSplit$home_team_goal[i]){
    leagueSplit$awayWin[i]=1
  }else{
    leagueSplit$awayWin[i]=0
  }
  if(leagueSplit$away_team_goal[i]<leagueSplit$home_team_goal[i]){
    leagueSplit$awayLose[i]=1
  }else{
    leagueSplit$awayLose[i]=0
  }
}

```


```{r}
library(dplyr)
#counting number of wins, loses, ties by team

#homeTie
homeTie<-leagueSplit %>%
  group_by(home_team_api_id, homeTie) %>%
  tally()
homeTie<-homeTie[homeTie$homeTie==1,] #removing cases of 0
homeTie<-homeTie[,c(1,3)]
colnames(homeTie)=c("team_api_id", "n_home_tie")

#home win
homeWin<-leagueSplit %>%
  group_by(home_team_api_id, homeWin) %>%
  tally()
homeWin<-homeWin[homeWin$homeWin==1,] #removing cases of 0
homeWin<-homeWin[,c(1,3)]
colnames(homeWin)=c("team_api_id", "n_home_win")

#home lose
homeLose<-leagueSplit %>%
  group_by(home_team_api_id, homeLose) %>%
  tally()
homeLose<-homeLose[homeLose$homeLose==1,] #removing cases of 0
homeLose<-homeLose[,c(1,3)]
colnames(homeLose)=c("team_api_id", "n_home_lose")

#awayTie
awayTie<-leagueSplit %>%
  group_by(home_team_api_id, awayTie) %>%
  tally()
awayTie<-awayTie[awayTie$awayTie==1,] #removing cases of 0
awayTie<-awayTie[,c(1,3)]
colnames(awayTie)=c("team_api_id", "n_away_tie")

#away win
awayWin<-leagueSplit %>%
  group_by(home_team_api_id, awayWin) %>%
  tally()
awayWin<-awayWin[awayWin$awayWin==1,] #removing cases of 0
awayWin<-awayWin[,c(1,3)]
colnames(awayWin)=c("team_api_id", "n_away_win")

#away lose
awayLose<-leagueSplit %>%
  group_by(home_team_api_id, awayLose) %>%
  tally()
awayLose<-awayLose[awayLose$awayLose==1,] #removing cases of 0
awayLose<-awayLose[,c(1,3)]
colnames(awayLose)=c("team_api_id", "n_away_lose")

#merging into gamesPlayedAH
gamesPlayedAH<-merge(gamesPlayedAH,homeTie, by="team_api_id")
gamesPlayedAH<-merge(gamesPlayedAH,homeWin, by="team_api_id")
gamesPlayedAH<-merge(gamesPlayedAH,homeLose, by="team_api_id")
gamesPlayedAH<-merge(gamesPlayedAH,awayTie, by="team_api_id")
gamesPlayedAH<-merge(gamesPlayedAH,awayWin, by="team_api_id")
gamesPlayedAH<-merge(gamesPlayedAH,awayLose, by="team_api_id")

#checking
gamesPlayedAH$tot<-(gamesPlayedAH$n_home_tie+gamesPlayedAH$n_home_win+gamesPlayedAH$n_home_lose+gamesPlayedAH$n_away_tie+gamesPlayedAH$n_away_lose+gamesPlayedAH$n_away_win)
gamesPlayedAH$correct<-(gamesPlayedAH$totalPlayed==gamesPlayedAH$tot)
```

```{r}
#creating total win lose tie variables
gamesPlayedAH$totWin<-(gamesPlayedAH$n_home_win+gamesPlayedAH$n_away_win)
gamesPlayedAH$totLose<-(gamesPlayedAH$n_home_lose+gamesPlayedAH$n_away_lose)
gamesPlayedAH$totTie<-(gamesPlayedAH$n_home_tie+gamesPlayedAH$n_away_tie)

#creating percent win tie for totals
gamesPlayedAH$percWin<-(gamesPlayedAH$totWin/gamesPlayedAH$totalPlayed)*100
gamesPlayedAH$percLose<-(gamesPlayedAH$totLose/gamesPlayedAH$totalPlayed)*100
gamesPlayedAH$percTie<-(gamesPlayedAH$totTie/gamesPlayedAH$totalPlayed)*100

#breakdownwin home or away by total wins 
gamesPlayedAH$percWinHome<-(gamesPlayedAH$n_home_win/gamesPlayedAH$totWin)*100
gamesPlayedAH$percWinAway<-(gamesPlayedAH$n_away_win/gamesPlayedAH$totWin)*100

#breakdown win home or away by total games
gamesPlayedAH$percWinHomeTot<-(gamesPlayedAH$n_home_win/gamesPlayedAH$totalPlayed)*100
gamesPlayedAH$percWinAwayTot<-(gamesPlayedAH$n_away_win/gamesPlayedAH$totalPlayed)*100

```


```{r}
#exploritory statistics

#ordering data by the highest percent win
gamesPlayedAH[order(-gamesPlayedAH$percWin),]
#ordering data by highest percent win at home of all wins 
gamesPlayedAH[order(-gamesPlayedAH$percWinHome),]
#ordering by highest percent win away  of all wins 
gamesPlayedAH[order(-gamesPlayedAH$percWinAway),]
#ordering by highest percent win home by total games played
gamesPlayedAH[order(-gamesPlayedAH$percWinHomeTot),]
#odering by highest percent win away by total games played 
gamesPlayedAH[order(-gamesPlayedAH$percWinAwayTot),]

#frequency distribution of teams based on winning percentage
library(ggplot2)
plot_wins_freq <- 
  ggplot(gamesPlayedAH,aes(percWin))+geom_area(stat="bin",bins=10,fill="light blue")+xlab("Winning percentage")
plot_wins_freq

library(ggplot2)
plot_wins_home_freq <- 
  ggplot(gamesPlayedAH,aes(percWinHomeTot))+geom_area(stat="bin",bins=10,fill="light blue")+xlab("Winning percentage")
plot_wins_home_freq

```


```{r}
#extracting team attributes and matching to games
require(reshape)
library(dplyr)
#creating season variable for teams to merge with games accurately. Because the season runs from 09-05. calculations done in 09 are for that years season start year, while calculations done in 02 are done for the previous years season start year.
for (i in 1:length(Team_Attributes$date)){
  if(substr(Team_Attributes$date[i],6,7)=="09"){
    Team_Attributes$seasonStart[i]<-(substr(Team_Attributes$date[i],1,4))
  }
  if(substr(Team_Attributes$date[i],1,7)=="2016-02"){
    Team_Attributes$seasonStart[i]<-"2015"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2015-02"){
    Team_Attributes$seasonStart[i]<-"2014"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2014-02"){
    Team_Attributes$seasonStart[i]<-"2013"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2013-02"){
    Team_Attributes$seasonStart[i]<-"2012"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2012-02"){
    Team_Attributes$seasonStart[i]<-"2011"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2011-02"){
    Team_Attributes$seasonStart[i]<-"2010"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2010-02"){
    Team_Attributes$seasonStart[i]<-"2009"
  }
  if(substr(Team_Attributes$date[i],1,7)=="2009-02"){
    Team_Attributes$seasonStart[i]<-"2008"
  }
}


#seperating season to get the start year in order to merge with team attributes
for(i in 1:length(leagueSplit$season)){
  leagueSplit$seasonStart[i]<-substr(leagueSplit$season[i],1,4)
}

#creating identifier to merge game data to home team stats for that season

leagueSplit$p1<-paste0(leagueSplit$seasonStart, leagueSplit$home_team_api_id)
Team_Attributes$p1<-paste0(Team_Attributes$seasonStart, Team_Attributes$team_api_id)


#merging dfs and keeping all values to avoid ommitting any. !is.na is used to remove the values in merge that were caused by the p1 values from other leagues in Team_Attributes. By doing this we makes sure the exact same number of matches are being accounted for. This merge uses home team API. _Therefore the team stats bound to each game are for the home team. _
matchTeamAttHome <- merge(leagueSplit, Team_Attributes, by= "p1", all=FALSE)
#removing unnecessary columns 
matchTeamAttHome<- matchTeamAttHome[,-c(1,17,18,19,22,23,24,26,27,29,31,33,34,36,38,40,41,42)]
#renaming columns to merge
colnames(matchTeamAttHome)[7]<-"matchDate"
colnames(matchTeamAttHome)[16]<-"homeStatsTakenDate"
colnames(matchTeamAttHome)[17:24]<-c("homeBuildUpPlaySpeed", "homeBuildUpPlayPassing", "homeChanceCreationPassing", "homeChanceCreationCrossing", "homeChanceCreationShooting", "homeDefencePressure", "homeDefenceAggression", "homeDefenceTeamWidth")

#creating identifier to merge game data to away team stats for that season
leagueSplit$p2<-paste0(leagueSplit$seasonStart, leagueSplit$away_team_api_id)
Team_Attributes$p2<-paste0(Team_Attributes$seasonStart, Team_Attributes$team_api_id)
#merging match data and away team data using method specified above
matchTeamAttAway <- merge(leagueSplit, Team_Attributes, by= "p2", all=FALSE)
#removing all unneccessary columns 
matchTeamAttAway<- matchTeamAttAway[,-c(1:8,10:20,23:25,27,28,30,32,34,35,37,39,41,42,43,44)]
#renaming columns 
colnames(matchTeamAttAway)[2]<-"awayStatsTakenDate"
colnames(matchTeamAttAway)[3:10]<-c("awayBuildUpPlaySpeed", "awayBuildUpPlayPassing", "awayChanceCreationPassing", "awayChanceCreationCrossing", "awayChanceCreationShooting", "awayDefencePressure", "awayDefenceAggression", "awayDefenceTeamWidth")

#760 values missing from each set beacuse there are no stats on those teams in that year. no stats for the 2008/2009 season. No stats for teams taken before 2010. the first stats start in 02-2010, which are coded into the 2009/2010 season for the reason exlained above.

#merging home and away 
matchTeamAttHA<-merge(matchTeamAttHome, matchTeamAttAway, by="match_api_id")
```

```{r}
#creating outcome varibale for win, lose, tie for home team to be our categorical independent variable for the following models 
for (i in 1:nrow(matchTeamAttHA)){
  if(matchTeamAttHA$home_team_goal[i]==matchTeamAttHA$away_team_goal[i]){
    matchTeamAttHA$homeOutcome[i]="Tie"
  } 
  if(matchTeamAttHA$home_team_goal[i]>matchTeamAttHA$away_team_goal[i]){
    matchTeamAttHA$homeOutcome[i]="Win"
  }
  if(matchTeamAttHA$home_team_goal[i]<matchTeamAttHA$away_team_goal[i]){
    matchTeamAttHA$homeOutcome[i]="Lose"
  }
}
#making the Y a factor variable
matchTeamAttHA$homeOutcome<-as.factor(matchTeamAttHA$homeOutcome)
```


```{r}
library(nnet)
library(glmnet)
library(caret)
#splitting into training and testing randomly with %70 in training and 30% in testing 
set.seed(123)
sample <- sample.int(n = nrow(matchTeamAttHA), size = floor(.70*nrow(matchTeamAttHA)), replace = F)
train<- matchTeamAttHA[sample, ]
test<- matchTeamAttHA[-sample, ]

#removing extra columns, leaving only y and X
train<-train[,-c(1:9,11:16, 25)]
test<-test[,-c(1:9,11:16,25)]
#multinomial logistic regression with lasso 
#converting from df to matrix 
X<-as.matrix(train[,-17])
Y<-train[,17]
testX<-as.matrix(test[,-17])

fit.lasso.cv<-cv.glmnet(X, Y, type.measure = "mse", alpha=1, family="multinomial")

fit.lasso.best<-glmnet(X,Y,family = "multinomial", alpha=1, lambda=fit.lasso.cv$lambda.min)

fit.lasso.pred<-predict(fit.lasso.best, testX, type="response")

predicted <- colnames(fit.lasso.pred)[apply(fit.lasso.pred,0,which.max)]
predicted
table(predicted, test[,17])
(31+288)/648

```
```{r}

# fit a gernalized linear regression using a logit link function, set distribution of the response variable to be binomial
glm.fit.lasso = glm(Y ~ X,
              data = train, 
              family = binomial)
glm_probs = predict(glm_fit, type = "response")
glm_pred = rep("Lose", 2280)
# For predicted probabilities greater than 0.5, assign Y to be "Win" otherwise assign Y to be "Lose"
glm_pred[glm_probs > .5] = "Win"
# Confusion matrix
table(glm_pred, matchTeamAttHA$homeWin)
(47 + 1003) / 1140



```

```{r}
#support Vector Machine 
library(e1071)

svmfit<-svm(homeOutcome~homeBuildUpPlaySpeed+ homeBuildUpPlayPassing+homeChanceCreationPassing+homeChanceCreationCrossing+homeChanceCreationShooting+ homeDefencePressure+homeDefenceAggression+homeDefenceTeamWidth+awayBuildUpPlaySpeed+awayBuildUpPlayPassing+awayChanceCreationPassing+awayChanceCreationCrossing+awayChanceCreationShooting+awayDefencePressure+awayDefenceAggression+awayDefenceTeamWidth, data=train, kernel = "linear", cost=2, scale=FALSE)

tune.out<-tune(svm, homeOutcome~homeBuildUpPlaySpeed+ homeBuildUpPlayPassing+homeChanceCreationPassing+homeChanceCreationCrossing+homeChanceCreationShooting+ homeDefencePressure+homeDefenceAggression+homeDefenceTeamWidth+awayBuildUpPlaySpeed+awayBuildUpPlayPassing+awayChanceCreationPassing+awayChanceCreationCrossing+awayChanceCreationShooting+awayDefencePressure+awayDefenceAggression+awayDefenceTeamWidth,data=train, kernal="linear", ranges=list(cost=c(0.001, 0.01, 0.1, 1, 5, 10, 100)))
summary(tune.out)
bestmod = tune.out$best.model
summary(bestmod)
ypred = predict(bestmod, test)
table(predict = ypred, truth = test$homeOutcome)
(57+4+267)/684





#binomial


svfmfitB<-svm(homeWin~homeBuildUpPlaySpeed+ homeBuildUpPlayPassing+homeChanceCreationPassing+homeChanceCreationCrossing+homeChanceCreationShooting+ homeDefencePressure+homeDefenceAggression+homeDefenceTeamWidth+awayBuildUpPlaySpeed+awayBuildUpPlayPassing+awayChanceCreationPassing+awayChanceCreationCrossing+awayChanceCreationShooting+awayDefencePressure+awayDefenceAggression+awayDefenceTeamWidth, data=train, kernel = "linear", cost=1, scale=FALSE)

plot(svmfit, train)

tune.outB<-tune(svm, homeWin~homeBuildUpPlaySpeed+ homeBuildUpPlayPassing+homeChanceCreationPassing+homeChanceCreationCrossing+homeChanceCreationShooting+ homeDefencePressure+homeDefenceAggression+homeDefenceTeamWidth+awayBuildUpPlaySpeed+awayBuildUpPlayPassing+awayChanceCreationPassing+awayChanceCreationCrossing+awayChanceCreationShooting+awayDefencePressure+awayDefenceAggression+awayDefenceTeamWidth,data=train, kernal="linear", ranges=list(cost=c(0.001, 0.01, 0.1, 1, 5, 10, 100)))
summary(tune.outB)
bestmodB = tune.outB$best.model
summary(bestmodB)
ypredB = predict(bestmodB, test)
table(predict = ypredB, truth = test$homeWin)


```


